### ISSUE TITLE
(QUESTION)Mod updating food/recipes for map

### ISSUE THREAD

**Issue by TheAlexPa** [Fetty42/FS22_AnimalFoodOverview#6]
Hi, i have 2 Animal Food Additions in my mods folder (1 original edited and a copy with a different name and an edited file, this for playing different maps with their proper additions) i was wondering if there is the possibilty to change the recipes/food shown in this mod, based on the animal food addition actually active (ex. while playing on NEU Minibrunn map, i still see alfalfa recipes/foods wich is not available as crop on map, and also i cant see "field grass" (map custom crop) as new food for chickens)

**Comment by Fetty42** [comment]
Hi, 
if I understood correctly, you are playing with the mods FS22_MaizePlus and FS22_maizePlus_animalFoodAdditions.
Normally MaizePlus/FS22 already checks, if a used food exists as filetype. 
For example, I get the following error message in my log file:
2024-08-17 06:07   Warning ... /FS22_maizePlus_animalFoodAdditions/maizePlus_animalFood.xml): FillType 'CHICKENFEED' not defined. Ignoring it

In your case with alfalfa, these not exist as a fruittype (Crop) but as a filltype.

**Comment by TheAlexPa** [comment]
so to see for example "Field Grass" in the recipes, i should add it as filltype in the MaizePlus Additions?

**Comment by Fetty42** [comment]
In general, my mod only shows what is correctly registered as food by the map or by mods such as FS22_MaizePlus in the game.

Without MaizePlus, the following is displayed:
![image](https://github.com/user-attachments/assets/09c691d4-f9d5-496e-a755-5a6fa28d1430)

The map Neu-Minibrunn comes with a adapted maizePlus_animalFood.xml.
If you use FS22_MaizePlus + FS22_maizePlus_animalFoodAdditions + the ‘maizePlus_animalFood.xml’ from the map, the following is displayed:
![image](https://github.com/user-attachments/assets/d74e458d-f231-483b-b40d-0d196efd82d0)

Are you sure that your adaptions are loaded correctly?

**Comment by Fetty42** [comment]
Sorry, but I forgot to switch to English for the screenshots

**Comment by TheAlexPa** [comment]
i'm not sure, can it be a problem if i renamed one of the animal food additions mod?
![Immagine 2024-08-18 014003](https://github.com/user-attachments/assets/236d99f3-aa95-4544-abf1-6915912a5525)
(this is in my mod folder)
On the minibrunn map i use the Additions_MINIBRUNN; on the other map i use the default

**Comment by Fetty42** [comment]
Yes, this will be the problem. MaizePlus searches explicitly for "FS22_maizePlus_animalFoodAdditions"

**Comment by TheAlexPa** [comment]
Oh, that's the problem... do you know if there is a chance to make them co-exist without switching .xml everytime?

**Comment by Fetty42** [comment]
Yes, that would have been my first idea too :)
